version: "3.7"
services:
  quotes:
    build:
      context: .
      target: develop
    entrypoint: "/app/start.dev.sh"
    command: "--reload"
    container_name: quotesapi
    environment:
      - DB_HOST=localhost
      - DB_NAME=quotesdb
      - DB_USER=quotes
      - DB_PASS=passpass
      - LOG_LEVEL=debug
    networks:
      - default
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./src:/app/src

  db:
    container_name: quotesdb
    environment:
      - POSTGRES_USER=quotes
      - POSTGRES_PASSWORD=passpass
      - POSTGRES_DB=quotesdb
    image: postgres:12.2-alpine
    networks:
      - default
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - .db:/var/lib/postgresql/data
